### ISSUE TITLE
Fix the og:image property

### ISSUE THREAD

**Issue by xaviablaza** [UXSoc/uxsoc-website#52]
## Description
- The og:image property does not properly render

## Solution
- Use the raw image here: https://i.imgur.com/DKAmvO4.jpg

Use the URL above here:
- [Community.js](https://github.com/UXSoc/uxsoc-react-app/blob/b1e6c0454be2c62fc82105cad674e77125a8588a/src/components/pages/Community/Community.js#L39)
- [Work.js](https://github.com/UXSoc/uxsoc-react-app/blob/b1e6c0454be2c62fc82105cad674e77125a8588a/src/components/pages/Work/Work.js#L42)
- [Home.js](https://github.com/UXSoc/uxsoc-react-app/blob/b1e6c0454be2c62fc82105cad674e77125a8588a/src/components/pages/Home/Home.js#L35)
- [About.js](https://github.com/UXSoc/uxsoc-react-app/blob/b1e6c0454be2c62fc82105cad674e77125a8588a/src/components/pages/About/About.js#L65)

**Comment by Hjkun77** [comment]
It works na og:image in facebook.
