### ISSUE TITLE
Change text-align in mobile

### ISSUE THREAD

**Issue by Hjkun77** [UXSoc/uxsoc-website#55]
All text-align: center in mobile should be text-align: left

**Comment by cobbie** [comment]
<img width="323" alt="screen shot 2019-02-08 at 12 49 44 am" src="https://user-images.githubusercontent.com/38446842/52428374-c84c8180-2b3c-11e9-8961-956759df1bc3.png">
<img width="375" alt="screen shot 2019-02-08 at 12 49 51 am" src="https://user-images.githubusercontent.com/38446842/52428375-c8e51800-2b3c-11e9-8126-570eef3cd0b9.png">
<img width="332" alt="screen shot 2019-02-08 at 12 52 04 am" src="https://user-images.githubusercontent.com/38446842/52428376-c8e51800-2b3c-11e9-94f0-713e67683639.png">
<img width="363" alt="screen shot 2019-02-08 at 12 52 11 am" src="https://user-images.githubusercontent.com/38446842/52428378-c8e51800-2b3c-11e9-94c7-e0589fa7a9d9.png">




Edited all text-align to left in mobile
