### ISSUE TITLE
Margin-bottom mobile fix

### ISSUE THREAD

**Issue by Hjkun77** [UXSoc/uxsoc-website#58]
Distance between "About the Event" and event description is far in mobile

![fix1](https://user-images.githubusercontent.com/38162086/52129323-32af7e80-2672-11e9-9a03-aa126e000015.jpg)

**Comment by cobbie** [comment]
<img width="260" alt="screen shot 2019-02-07 at 10 12 09 pm" src="https://user-images.githubusercontent.com/38446842/52428143-5aa05580-2b3c-11e9-822a-dd048ac01b70.png">
